---
- name: Install GOSDK on the server using gantsign.golang role
  hosts: server
  roles:
  - gantsign.golang

- name: Install Prometheus, and NodeExporter on the server using cloudalchemy collections/role
  hosts: server
  roles:
  - cloudalchemy.node_exporter
  - cloudalchemy.blackbox_exporter
  - cloudalchemy.prometheus

- name: Running Golang application on the server
  hosts: server
  roles:
  - golang.app
