---
- name: Copy Golang app folder to the server 
  ansible.builtin.copy:
    src: /home/runner/work/devops-monitoring-task/devops-monitoring-task/go-app/
    dest: /home/ubuntu/golang-app
    mode: '0777'

- name: Install app dependencies
  ansible.builtin.command: 
    chdir: "/home/ubuntu/golang-app"
    cmd: |
      go build .
      chmod u+x app
      ./app
  async: 1000
  poll: 0  

- name: App debugging
  become: true
  ansible.builtin.shell: 
    ps aux | grep go 
    netstat -tulpn | grep LISTEN
  register: app_status
- name: App status
  ansible.builtin.debug: msg={{ app_status.stdout_lines }}

