name: "Run Ansible Playbook"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  # server_provisioning:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run Ansible Playbook
  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.1.7
  #     - run: cd ./terraform
  #     - run: terraform init
  
  setup_ansible:
    needs: server_provisioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup server
        run: |
          echo "ping..............."
  
  run_ansible:
    runs-on: ubuntu-latest
    needs: setup_ansible
    steps:
      - uses: actions/checkout@v2
      - run: |
          ansible --version
          pipx inject ansible-core jmespath
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with: 
          directory: ./ansible_files
          playbook: playbook.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}

