name: "Run Ansible Playbook"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Multiple commands
        run: |
          pwd
          ls -la
      - name: Setup ansible
        run: |
          ansible --version
          pipx inject ansible-core jmespath
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with: 
          directory: ./ansible_files
          playbook: ansible_files/playbook.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
