name: "Run Ansible Playbook"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: logikal-code/pip-install@{release}
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with: 
          directory: ansible_files/
          playbook: playbook.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
